package gg

import (
	"flag"
	"fmt"
	"io"
	"net/url"
	"os/exec"
	"strings"
)

var Version string

const (
	ExitCodeOK = iota
	ExitCodeNG
)

const CLIName = "gg"

const Help = `
usage:
  %s [option] [word word word...]
        search words by the default web browser

option:
`

type CLI struct {
	OutStream io.Writer
	ErrStream io.Writer
	OS        string
}

func (cli *CLI) Run(args []string) (exitCode int) {
	ggFlag := flag.NewFlagSet(CLIName, flag.ContinueOnError)
	ggFlag.SetOutput(cli.ErrStream)
	ggFlag.Usage = func() {
		fmt.Fprintf(cli.ErrStream, Help, CLIName)
		ggFlag.PrintDefaults()
	}

	var optVersion bool
	ggFlag.BoolVar(&optVersion, "version", false, "print version and exit")

	err := ggFlag.Parse(args)
	if err != nil {
		return ExitCodeNG
	}

	if optVersion {
		v, err := cli.Version(Version)
		if err != nil {
			fmt.Fprintf(cli.ErrStream, "%s\n", err)
			return ExitCodeNG
		}
		fmt.Fprintf(cli.OutStream, "%s\n", v)
		return ExitCodeOK
	}

	opener := cli.Opener()
	if opener == "" {
		fmt.Fprintf(cli.ErrStream, "Unsupported OS")
		return ExitCodeNG
	}

	addr := cli.Addr(ggFlag.Args())
	fmt.Fprintf(cli.OutStream, "%s %s\n", opener, addr)
	cmd := exec.Command(opener, addr)
	err = cmd.Run()
	if err != nil {
		fmt.Fprintf(cli.ErrStream, "%s\n", err)
		return ExitCodeNG
	}
	return ExitCodeOK
}

func (cli *CLI) Opener() (opener string) {
	switch cli.OS {
	case "linux":
		opener = "xdg-open"
	case "darwin":
		opener = "open"
	default:
		opener = ""
	}
	return opener
}

func (cli *CLI) Addr(words []string) (addr string) {
	params := url.Values{}
	params.Add("q", strings.Join(words, " "))
	addr = "https://www.google.co.jp/search?" + params.Encode()
	return addr
}

// Version creates version string.
// v is expected to be generated by "git describe --dirty --tags".
//
// example: "v0.0.1-2-gcbaffea-dirty"
func (cli *CLI) Version(v string) (string, error) {
	a := strings.Split(v, "-")
	if len(a) > 2 {
		return fmt.Sprintf("%s version %s, build %s", CLIName, a[0][1:], a[2]), nil
	}
	return "", fmt.Errorf("\"%s\" is not expected string format.", v)
}
